/* autogenerated by Processing revision 1289 on 2023-01-31 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Interactive_Art__1 extends PApplet {

//Azaria Dunston
//Jan 31, 2023
//Interactive Art Project

public void setup(){
  /* size commented out by preprocessor */;
  background(255, 255, 255);
  /* smooth commented out by preprocessor */;
}

public void draw(){
  fill(0, 0, 0);
  textSize(20);
  text("Click to clear screen \n Press SPACE for white background", 0, 20);
  
  //Change colors
  if (mouseY < height/2){
    fill(200, 100, 100);
    if (mouseX > width/2) {
      fill(100, 200, 100);
    }
  }
  else{
    fill(100, 100, 200);
    if (mouseX < width/2) {
      fill(225, 175, 75);
    }
  }
  
  //change shapes
  if (mouseX < width/2){
    ellipse(mouseX, mouseY, 50, 50);
  }
  else if (mouseX > width/2){
    beginShape();
      vertex(mouseX, mouseY - 25);
      vertex(mouseX + 20, mouseY + 10);
      vertex(mouseX - 20, mouseY + 10);
      vertex(mouseX, mouseY - 25);
     endShape(CLOSE);
  }
  
}

//Changes background color
public void mouseClicked(){
  //background(255, 255, 255);
  if (mouseY < height/2){
    background(255, 200, 200);
    if (mouseX > width/2) {
      background(200, 255, 200);
    }
  }
  else{
    background(200, 200, 255);
    if (mouseX < width/2) {
      background(250, 200, 100);
    }
  }
}

//white background
public void keyPressed(){
  if(key == ' '){
    background(255, 255, 255);
  }
}


  public void settings() { size(1000, 1000);
smooth(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Interactive_Art__1" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
